name: Generate and Deploy Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Wrangler
      run: npm install -g @cloudflare/wrangler

    - name: Generate sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://1t2.pages.dev

    - name: Deploy to Cloudflare Pages
      run: wrangler pages publish . --project-name your-project-name
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
